/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Codificar;
import control.Decodificar;

/**
 *
 * @author Ramón Bogarin y Ricardo Avila 
 */
public class Bogav extends javax.swing.JFrame {

    /**
     * Creates new form Bogav
     */
    public Bogav() {
        initComponents();
        opcionesEncriptacion.add(espaniol);
        opcionesEncriptacion.add(bogav);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesEncriptacion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        leer = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        escribir = new javax.swing.JTextArea();
        espaniol = new javax.swing.JRadioButton();
        bogav = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leer.setColumns(20);
        leer.setRows(5);
        jScrollPane1.setViewportView(leer);

        escribir.setColumns(20);
        escribir.setRows(5);
        jScrollPane2.setViewportView(escribir);

        espaniol.setText("Bogav a Español");
        espaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaniolActionPerformed(evt);
            }
        });

        bogav.setText("Español aBogav");
        bogav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bogavActionPerformed(evt);
            }
        });

        jLabel1.setText("Leer el idioma o codificacion:");

        jLabel2.setText("Escribir el idioma o codificacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espaniol)
                            .addComponent(bogav)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel2)
                    .addContainerGap(161, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(espaniol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bogav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel2)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void espaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaniolActionPerformed

      Thread hilo=new Thread(new Runnable() {

        
          public void run() {
           Decodificar obj=new Decodificar();
           obj.setTraducir(escribir.getText());
        
        do{ 
            obj.setIntroducir(obj.getCaracterPalabra());
            obj.setaumentoPuntador();
        }while(obj.getPosicionDelPuntador()<obj.getPalabraTamaño());
        leer.setText(""); 
        leer.setText(obj.toString());
          }
      });
      
      hilo.start();
       
       
    }//GEN-LAST:event_espaniolActionPerformed

    private void bogavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bogavActionPerformed
        Thread hilo=new Thread(new Runnable() {

        
          public void run() {
            
            Codificar obj=new Codificar();
            obj.setTraducir(escribir.getText());
            do{
                if(obj.getCaracterPalabra()>='a'&& obj.getCaracterPalabra()<='z' || obj.getCaracterPalabra()>='A' && obj.getCaracterPalabra()<='Z'){
                 obj.setMayusculasBogav(obj.getCaracterPalabra());
                 obj.setMinusculasBogav(obj.getCaracterPalabra());
                } else{
                 obj.setcaracterEspecialBogav1ra(obj.getCaracterPalabra());
                 obj.setCaracterEspecialBogav2(obj.getCaracterPalabra());
                }
                obj.setaumentoPuntador();
            }while(obj.getPosicionDelPuntador()<obj.getPalabraTamaño());
            leer.setText(""); 
            leer.setText(obj.toString());
          }
      });
      
      hilo.start();
    }//GEN-LAST:event_bogavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bogav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bogav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bogav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bogav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bogav().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bogav;
    private javax.swing.JTextArea escribir;
    private javax.swing.JRadioButton espaniol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea leer;
    private javax.swing.ButtonGroup opcionesEncriptacion;
    // End of variables declaration//GEN-END:variables
}
